### ISSUE TITLE
file

### ISSUE THREAD

**Issue by muxi-0104** [YuetongXU/Cropgbm-genomebiology#1]
where is the file"Genotype.female_1428_012.txt"?

**Comment by YuetongXU** [comment]
The genotype file was not uploaded because it was too large. If you want, you can download it from the link of the article CUBIC: an atlas of genetic architecture promises directed maize improvement (https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-1930-x). Or you can download it at http://maizego.org/Resources.html.

**Comment by YuetongXU** [comment]
The downloaded data may be unprocessed, and you need to perform necessary preprocessing on the data yourself, such as filtering SNPs with maf<0.05, miss<0.1, etc.

**Comment by muxi-0104** [comment]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thank you for your reply. I am a student and I have benefited a lot from your article. I want to do further research, but I feel sorry I can't find the documents I need on the website. And I can't download the data according to the website you prompted. Is it convenient for you to provide more detailed documents？The following files I can not find:
'/data/YanJ/PROJECT/cropGBM/'
'/data/xyt/data_female_1428/'
'/data/xyt/G3_6species/'






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuetongXU/Cropgbm-genomebiology"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuetongXU/Cropgbm-genomebiology] file (Issue #1)





 
The downloaded data may be unprocessed, and you need to perform necessary preprocessing on the data yourself, such as filtering SNPs with maf<0.05, miss<0.1, etc.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YuetongXU** [comment]
I'm glad my work has been recognized by you and can help you. The file path you provided is my local path, sorry for the confusion. I'm guessing you want genotype data and phenotype data for these groups? Due to the attribution of the data involved, all the data in our article are from the following databases and cannot be provided separately in the name of this article. Here are the sources of each data:

G3 6species, https://doi.org/10.1534/g3.119.400498

Female 1428 and F1, https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-1930-x. Or you can download it at http://maizego.org/Resources.html.

**Comment by muxi-0104** [comment]
&nbsp;&nbsp;&nbsp;&nbsp; I am glad you can reply and help me. I'm sorry to disturb you so late.&nbsp; Your work really help me. We will continue to learn from your team. Thank you very much.
&nbsp;&nbsp;&nbsp; Best Regards.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YuetongXU/Cropgbm-genomebiology"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月22日(星期六) 晚上10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YuetongXU/Cropgbm-genomebiology] file (Issue #1)





 
I'm glad my work has been recognized by you and can help you. The file path you provided is my local path, sorry for the confusion. I'm guessing you want genotype data and phenotype data for these groups? Due to the attribution of the data involved, all the data in our article are from the following databases and cannot be provided separately in the name of this article. Here are the sources of each data:
 
G3 6species, https://doi.org/10.1534/g3.119.400498
 
Female 1428 and F1, https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-1930-x. Or you can download it at http://maizego.org/Resources.html.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YuetongXU** [comment]
Glad to help you, best wishes.
